apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: "index.docker.io/divesh987/web:latest"  
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

      - name: db
        image: "index.docker.io/divesh987/db:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
# vim: set ts=2 expandtab!: